[build]
  command = "npm run build"
  publish = "dist"
  
  # Point Netlify to the folder containing our serverless functions
  functions = "api"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200